# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20b3992389cfc1d08d49f5ce381acb5215a68ccc9cd719862c5dc1e6679f1ea7ac264bfb79373a4ef2f5d1dbd8f7a0e761bf6655c6196e01829c366cbbd04f30

test:
  secret_key_base: 878d532387235c09503ad600ff9423354d61373f1ddd36dd28944b957d70b4ba072f419bbdd8885eb86910e7442d367e98252e649a39905298f41e1dc813e725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
